### ISSUE TITLE
QA: related paper on kGraph?

### ISSUE THREAD

**Issue by shenxiangzhuang** [boniolp/kGraph#1]
Hi, Paul! I'm wondering if there will be a paper on kGraph?

I've been keeping an eye on your work since series2graph, which is a great algorithm, and the same goes for kGraph in my opinion.

**Comment by boniolp** [comment]
Hi Mathew Shen!

Thank you for your interest in kGraph (and Series2Graph). The paper has not yet been published, but I will let you know when it is!

Best,

Paul
